# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: install jest
        run: npm i -g jest
      - name: install deps
        run: npm i --prefix ./api_tests
      - name: Run integration tests
        run: ./api_tests/run_integration_tests.sh
      #- uses: actions-rs/toolchain@v1
      #with:
      #toolchain: stable
      #- uses: actions-rs/cargo@v1
      #with:
  #converage:
  #name:                       coverage
  #runs-on:                    ubuntu-latest
  #container:
  #image:                    <your [CI] docker image with installed tarpaulin>
  #options:                  --security-opt seccomp=unconfined
  #steps:
  #- name:                   Checkout repository
  #uses:                   actions/checkout@v2

  #- name:                   Generate code coverage
  #run: |
  #cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

  #- name:                   Upload to codecov.io
  #uses:                   codecov/codecov-action@v1
  #with:
  ## token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
  #fail_ci_if_error:     true         #command: test
