[package]
name = "nettu-booking"
version = "0.1.0"
authors = ["Fredrik Meringdal <fmeringdal@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrule="0.3.7"
chrono = "0.4.19"
chrono-tz = "0.5.3"
